const RECIPES_DATA = [
  {
    title: 'Ondřejovy Brioche Buns',
    order: 6,
    url: 'ondrejovy-brioche-buns',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/dreceptar.appspot.com/o/brioche-buns.jpg?alt=media&token=fd041f09-6924-4b17-85a7-863039293ec7',
    createdAt: '14. 5. 2020',
    leadText: 'Recept na briošky inspirovaný francouzským pekařem. Upravená verze bez mléka, navíc ještě vláčnější. Dají se použít na hambáče, snídaňové toasty plněné vajíčkem a slaninou nebo klidně nasladko s marmoškou.',
    ingredients: [
      '1000 g hl. mouka na kynuté těsto (100 %)',
      '300 g vody 33°C (30 %)',
      '6x vejce M (30 %)',
      '200 g nemáslo (20 %)',
      '100 g cukr (10 %)',
      '20 g sůl (2 %)',
      '14 g sušené droždí (1,5 %)',
    ],
    instructions: [
      'Voda do mísy. Moc studená neaktivuje droždí, moc teplá zabije droždí. Ideál je 33°C.',
      `Vsypat droždí a rozpustit ve vodě jemným mícháním. Důležité! Po přidání každé ingredience se musí vše pořádně rozmíchat, aby vznikla jednotná hmota. V průběhu nepřidávat ani mouku ani vodu, vše se i tak spojí.`,
      'Přidat vejce a pečlivě rozmíchat.',
      'Přidat cukr a sůl a rozpustit.',
      'Přidat rozpuštěné máslo, ne moc teplé (max  36°C, pokud byla studená vajíčka a je např. zima, máslo může být teplejší, aby ohřálo zbytek těsta na ideální teplotu pro droždí), a pečlivě rozmíchat.',
      'Nakonec vsypat mouku a hníst v robotu aspoň 10 minut na rychlost 4.',
      'Kouli těsta vložíme do kryté nádoby a necháme kynout při pokojové teplotě.',
      'Po 30 min první stretch & fold.',
      'Po dalších 30 min druhý stretch & fold.',
      'Není podmínka. Těsto dáme do ledničky (4°C) a necháme zrát okolo 9 h. Každých 9°C dvojnásobí/půlí rychlost fermentace. Čím pomalejší kynutí, tím komplexnější chuť.',
      'Těsto vyndat z lednice a nechat 1 h při pokojové teplotě.',
      'Rozdělit na 20 stejných částí (95g, Amálka 50 g).',
      'Tvarování bulky. Přeložit ze všech stran, ohyby dolů a košíčkem z ruky dotahovat bulku kroužením po stole. Malíček a palec pořád na stole.',
      'Bulky nechat odpočinout cca 20 min, jemně rozplácnout, znovu přeložit a vytvarovat kroužením po stole znovu do tvaru bulky. Čím víc dotaženější budou, tím víc budou kynout nahoru a ne do stran.',
      'Naskládat na plech, přikrýt utěrkou, aby nezaschly a nechat vykynout 2 h – v teple! Dokud pořádně nevykynou, nepéct!', 
      'Po vykynutí jemně! a rovnoměrně potřít rozmíchaným vajíčkem s kapkou nemléka.',
      'Péct na 180°C (horkovzduch) cca 12 minut na střední pozici.',
      'Po vyndání z trouby nechat odpočinout pod utěrkou.',
    ]
  },
  {
    title: 'Ondřejova Pizza Napoletana',
    order: 2,
    url: 'ondrejova-pizza-napoletana',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/dreceptar.appspot.com/o/pizza-napoletana.jpg?alt=media&token=8718ebdf-ed76-4a1d-8c22-08bbc31fbb45',
    createdAt: '25. 6. 2020',
    leadText: 'Tady není o čem. Na 9/10 to jde i bez pece. Dejte pizze čas vyzrát, co nejvyšší teplotu, moc dlouho ji v troubě nesušte a ona se vám náležitě odvděčí. Vše v receptu má své opodstatnění. Recept je považován za zážitkový a podmínkou jeho užívání je sdílení s rodinou nebo přáteli.',
    ingredients: [
      '800 g hl. mouka babišina na pizzu (100 %)', 
      '560 g voda (70 %)',
      '22 g sůl (2,75 %)',
      '1,6 g čerstvé droždí (0,2 %)',
    ],
    instructions: [
      'Do vody vsypat sůl a zcela rozmíchat.',
      'Přidat cca 10 % mouky a rozmíchat.',
      'Až nyní přidat rozdrobené droždí, pečlivě rozmíchat.',
      'Dosypat mouku a uhníst na rychlost 4 cca 5 minut.',
      'Nechat odpočinout 30 minut.',
      'Hníst dalších 20 minut a vybudovat pořádnou sílu těsta.',
      'Dokončit dotahováním koule na stole, do hladka. Zpočátku může trošku lepit, nepodsypávat ani nenamáčet!',
      'Finální stretch&fold a dotažení.',
      'Kouli vložíme do zakryté mísy a necháme v teplejším prostředí 1 hodinu kynout (moc nenakyne).',
      'Po hodině těsto vyklopíme a rozdělíme na jednotlivé pizzy. 6x 200 g menší osobní pizza + 1x Amálka 150 g.',
      'Vytvoříme pořádně dotažené "mozzarely", které naskládáme do nádoby na kynutí vysypané moukou. Pizzy poprášíme moukou a pečlivě zakryjeme, aby se tam nedostal žádný vzduch a neokoraly.',
      'Necháme fermentovat. Po 4 hodinách pokojového kynutí je těsto už použitelné. Po 24 h kynutí v lednici je ideální. V lednici uchovat maximálně 7 dní, záleží na vnitřní teplotě.',
      'Před pečením necháme 2 h v pokojové teplotě a stále zakryté.',
      'Pizzu tvarujeme tak, jak kynulo, vršek je vršek a spodek je spodek. Posypeme a podsypeme krupičkou/semolinou (už ne moukou!).',
      'Plochou prstů tvarujeme okraj, který nikdy nemačkáme, stejně tak moc nemačkáme střed. Když už víc mačkat nejde, bereme pizzu na pěsti a rozházíme si jí do požadované velikosti nebo ji vyfackujeme.',
      'Lopatu posypeme semolinou/krupicí a přehodíme na ní pizzu. Doroztáhneme do požadované velikosti. Ozdobíme a moc to nezdržujeme, aby se sugo nepropilo a tím nepřilepilo těsto k lopatě. Na okraje lehce oliváč. Čas od času můžeme těstem na lopatě pošoupnout.',
      'Otevřeme rozpálenou troubu na max (zapnutou alespoň hodinu před pečením), tím termostat začne troubu dohřívat, pizzu položíme na ocelový plát a necháme 60 s. Poté zašoupneme dovnitř a zavřeme. Po 120 s vyndaváme.',
      'Necháme odpočinout na mřížce a dosprejujeme oliváčem.',
    ],
    tips: [
      'Každých 9°C dvojnásobí/půlí rychlost fermentace, čím pomalejší kynutí, tím komplexnější chuť těsta.',
      'Když těsto při hnětení moc lepí, stačí chvíli počkat, nepřisypávat mouku!',
      'Při nízké teplotě bude pizza ještě před zhnědnutím suchá a tvrdá a sýr pustí vodu. A to nechceš.',
      'Nepředtvarovávat okraje, vzduch se pak nedostane do krusty.',
      'Na ocel nepošupovat, ale jen odtahovat k sobě, aby se pizza nesmrskla.',
      'Pozor na olej na lopatě.',
    ],
  },
  {
    title: 'Ondřejův Sourdough Bread',
    order: 1,
    url: 'ondrejuv-sourdough-bread',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/dreceptar.appspot.com/o/sourdough-bread.jpg?alt=media&token=a2f78416-b463-4160-b87c-317e418a4c8c',
    createdAt: '17. 5. 2021',
    leadText: 'Dospět k tomuto finálnímu receptu mě stálo hodně úsilí. Verzí bylo něco málo pod 20 a tahle se osvědčila nejvíce. U kváskového chlebu je tolik proměnných, které musíte splnit na jedničku, že selhání není nic neobvyklého. Než jsem upekl chleba, se kterým jsem byl spokojený alespoň na 8/10, zabralo mi to půl roku. Proto si važte každé doprobrobna rozepsané informace, recept je sice obsáhlejší, možná vás ale zachrání od zklamání a rozteklé, tuhé placky. Příprava zabere dost času, buďte trpěliví. Chcete přece pořádně vysoký a měkkoučký krajíc s jemně křupavou kůrčičkou, že?',
    ingredients: [
      '700 g hl. pš. babišina chlebová',
      '300 g hl. pš. celo. nature-promises',
      'babišina hl. žit. tm. na krmení',
      'rýžová mouka',
      '700 g filtrovaná voda',
      '225 g levain',
      '20 g sůl',
    ],
    instructions: [
      'KVÁSEK: Hladový a neaktivní kvásek vyndáme z lednice, necháme si z něj 20 g a zbytek vyhodíme. Nakrmíme ho 20 g žitné mouky (babišina žitná hladká tmavá) a 20 g filtrované vody. Pořádně promícháme, gumičkou označíme hladinu, kám těsto sahá, přikryjeme víčkem (nedotahovat) a dáme na teplé místo. Necháme ho minimálně zdvojnásobit. Silný kvásek by to na teplém místě měl stihnout do takových 4 hodin. Pokud to nestíhá, počkáme déle a proces opakujeme. Pokud byl kvásek v lednici třeba týden, krmení je dobré opakovat klidně 4x. Nakrmit večer před spaním a ráno. Když už je kvásek silný a aktivní, nekrmíme ho před spaním, ale už odpoledne (v pět, šest), aby před spaním byl v plné síle a my mohli založit levain. Kvásek na vrcholu je 2-4násobný, po stranách zaoblený. Jakmile se začne propadat dolů - je těsně za vrcholem.',
      'LEVAIN: Vezmeme 25 g kvásku na vrcholu jeho sil a rozmícháme ve 100 g filtrované vody, může být klidně studenější než pokojová, do rána je času dost. Přisypeme 100 g hl. celozrné pšeničné mouky a pořádně promícháme. Misku přikryjeme a necháme na lince do rána dozrát.',
      'MIX: Do mísy nalijeme 650 g vody cca 25°C. Vyškrábneme do ní všechen levain, který musí plavat na hladině (je tedy plný vzduchu). Lehce rozmícháme ve vodě a následně přidáme všechnu mouku. Důkladně promícháme, aby se všechna voda a mouka spojila.',
      'FERMENTOLYSE 1h: Místo zbytečného hnětení odležíme 1 h v zakryté míse a necháme těsto udělat práci za nás. Tomu se říká autolyse (když je součástí i kvásek - fermentolyse).',
      'SŮL: Připravíme si zbylých 50 g vody a 20 g jemně namleté soli. Nalijeme a nasypeme do těsta (klidně nadvakrát) a vpracujeme. Všemi pěti prsty děláme důlky do těsta. Občas těsto přeložíme a zase "propichujeme" z jiné strany.',
      'SLAP & FOLD 10 min: Až těsto přijme sůl a vodu, vytáhneme ho z mísy a dáme na pracovní plochu. Přibližně 6-10 minut provádíme techniku slap & fold, dokud těsto nepřestane lepit a nezíská "gumovější" strukturu. To znamená, že se úspěšně buduje lepek. V žádném případě nepřidáváme mouku. Ze začátku to bude možná těžké, ale s více zkušenostma se to zlepší. Nenechte se odradit lepivostí, když s těstem na vzduchu párkrát fláknete o pracovní plochu, po chvilce vám sleze z rukou. Rukavice ušetří dost práce s dostáváním těsta z rukou - jde to z nich krásně umýt. Když máme hotovo, těsto dotáhneme do koule (bez mouky - na mouce by těsto klouzalo) a vložíme zpět do mísy. Pozor, těsto se nesmí přetáhnout moc nebo se začne trhat. Necháme odpočinout 30 minut zakryté.',
      'STRETCH & FOLD 2x: Těsto podhrábnutím "odloupneme" od okrajů mísy a natáhneme a přehneme přes zbytek těsta ze všech světových stran. Sever, jih, východ, západ. Těsto taháme jen tak, abychom ho nepřetrhli. Pokud těsto lepí, nikdy nepřisypávame mouku, pomůžou spíše navlhčené ruce studenou vodou. Necháme 30 minut odpočinout a opakujeme ještě jednou.',
      'LAMINATION: Po druhém stretch & fold těsto vyndáme na pracovní plochu a necháme ho chvilku odpočinout. Už by mělo být trošku poddajnější a pružnější. Začneme ho roztahovat po ploše a necháme ho chvíli zrelaxovat. Pozor, ať se nepřetrhne. Tenké vrstvy pak přeskládáme přes sebe. To pomůže lepší fermentaci a zesílí těsto. Dotáhneme do koule a dáme do přikryté naolejované mísy (2 kapky oleje rozetřené papírovým kapesníčkem).',
      'KYNUTÍ: Jeho doba bude záležet na teplotě. Pokud je léto, bude to trvat méně než hodinu. V zimě nechávám mísu v mírně! předehřáté troubě (do 30°C). Po 1 h odkrýt mísu a nechat na vzduchu ještě 20 minut. Procentuální růst podle hydratace a množství bílkovin v mouce vysvětlovat nebudu, je to složitější alchymie, jen abyste věděli, že to existuje. Co dělám já - po slap&fold si uříznu vzorek těsta do frťanu, označím hladinu gumičkou a sleduju cca 15% růst. Ke konci už je to rychlé a těsto velmi rychle přezraje (pak se v troubě rozteče). Takže neřešte a dělejte všechno podle 100x upraveného receptu. :)',
      'PRESHAPING: Těsto v míse zlehka posypeme mixem rýžové mouky a hladké pšeničné (50:50). Rýžová mouka zařídí, že to nebude lepit. Vyklopíme ho na pracovní plochu. Moc se mu nebude chtít a my nechceme, aby se roztrhalo a všechen vybudovanej vzduch z něj unikl. Tak ho pomocí stěrky na těsto co nejrychleji odškrábneme ze dna a stran, ať těsto zůstane hezky v jednom celku. Rozdělíme na požadované díly - já dělám 2x 600g a 1x větší. Těsto JEMNĚ roztáhneme do všech světových stran a přeložíme zleva doprostřed a zprava doleva. Přeložené těsto rolujeme směrem od sebe. Lehce dotáhneme do koule a necháme odpočinout 15 minut na stole.',
      'SHAPING: Postup stejný jako preshaping. Chleba vložíme do mixem vysypané ošatky na kynutí. Klidně trošku víc, přebytečná mouka jde totiž před pečením oprášit. Ošatku přikryjeme potravinářskou fólií a dáme těsto dozrát do dolů do lednice - tam je totiž taková zima, že těsto přestane kynout (droždí hibernuje), jen si krásně sedne a dozraje. Necháme do druhého rána.',
      'PŘÍPRAVA TROUBY: Peču na litinovým tálu. 1cm pizza kámen nic moc. Na plechu to bude asi tragédie. Takže záleží na vás, co máte, co nakoupíte. Do trouby dám tál, na něj skleněnou pyrexovou mísu a předehřívám 1h na 230°C na horkovzduch. Kdo má dutch oven, peče v tom. Nepřikrytý chleba při pečení vyschne, přikrytý si udrží vlastní páru a krásně vyleze - tomu se říká oven spring.',
      'PEČENÍ: Pokud chleba projde tzv. poke-testem (šťouchacím testem) - po píchnutí prstem do chleba se těsto nesmí rychle vrátit do původní pozice. Musí se pomalu vracet a zůstat tam trošku důlek. Sundáme fólii, na ošatku položíme kousíček pečicího papíru, přiklopíme lopatou na pizzu/chleba/cokoliv a přetočíme vzhůru nohama. Na ošatku trošku zaklepeme a zaříkávadlem: "Bábovičko poveď se mi, jestli se mi nepovedeš, tak dostaneš NA PR DEL!" dostaneme chleba ven. Rychle ale něžně oprášíme přebytečnou mouku. Nařízneme žiletkou, ať má chleba kam vyrůst. Tomu se říká scoring. Od jednoho konce k druhému, jedním tahem, 45° sklon, 5 mm hluboko. Dáme do trouby a pořádně poprášíme vodou. Přikryjeme skleněnou mísou. Pečeme na 230°C horní spodní ohřev (ne horkovzduch) 25 minut přikryté. Odkryjeme a dopečeme do požadované barvy na 220-230°C cca 10-15 minut.',
      'PO PEČENÍ: Vyndáme z trouby a dáme vychladnout na kovovou mřížku. Přikryjeme utěrkou (kůrka bude křehčí) a necháme vychladnout minimálně 2 h, než budeme krájet. Jinak všechna pára unikne, nedostane se do kůrky a vnitřek chleba bude vyschlej. Chleba nakrájím na krajíce a dám do ikea uzavíratelnýho sáčku a zamrazim. Vždycky, když chci čerstvej krajíc chleba, vyndám ho z mrazáku a dám na 30-60 s do mikrovlnky na max. A je jak vytaženej z trouby.',
    ],
    tips: [
      'Slap & Fold: https://www.youtube.com/watch?v=9LXcchONCwg', 
      'Dotažení do koule: https://www.youtube.com/watch?v=v5t5MEZt6LM',
      'Stretch & Fold: https://www.youtube.com/watch?v=HprDjPWuiN8',
      'Preshaping: https://www.youtube.com/watch?v=Op-LKk-i4zQ',
      'Shaping: https://www.youtube.com/watch?v=h7eqwYLv2tI',
    ],
  },
  {
    title: 'Ondřejova Pho Ga',
    order: 4,
    url: 'ondrejova-pho-ga',
    leadText: 'PHOck MSG! Tohle fáčko vytuněné bůčkem je BEZ botkaně/MSG/glutamanu. Místo jedné lžičky zvýrazňovače chuti ve vývaru musíme táhnout 4 jabka a kedlubnu a s dochucením se opravdu mazlit. A ani to botkaň zcela nenahradí, ale pokud chceme mít Pho ve zdravější verzi, než které dostaneme v 99 % restaurací, musíme tenhle zvýrazňovač oželit. A věřte, že až recept ozkoušíte, nebudete ho zas tak postrádat. Glutamátů do sebe sypete každý den mraky, tak tady uděláme výjimku. Váš domácí vývar bude mnohem silnější a nebude jen falešně ovoněný. Dobrou chuť a chci slyšet pořádný srkání!',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/dreceptar.appspot.com/o/pho-ga.jpg?alt=media&token=bec29cce-b6fc-4224-8e43-0975e8d60fcd',
    createdAt: '7. 12. 2020',
    ingredients: [
      '5,5 l voda',
      '2 Kg kuřecí čtvrtky + něco na vývar',
      '1 Kg bůček',
      '4x jablko',
      '1x kedlubna',
      '2x cibule/větší šalotky',
      '2x jarní cibulka',
      '10 cm zázvor',
      '40x kardamom',
      '15x badyán',
      '10x skořice',
      '5x hřebíček',
      'hrst semínek koriandru',
      'rybí omáčka, citron, chilli',
      'koriandr a mungo klíčky',
      'nudle Pho'
    ],
    instructions: [
      'Omyté maso na vývar vložíme do hrnce, zalijeme studenou vodou, přidáme lžíci soli a cukru, oloupanou cibuli/šalotky, jednu ze dvou jarních cibulek, rozčtvrtěná jablka a kedlubnu a přivedeme k varu.',
      'S varem se začne uvolňovat bílkovina ve formě pěny, tu pečlivě sbíráme, abychom měli co nejčistší vývar.',
      'Po 30 - 60 min tažení vyndáme jablka, aby se nerozvařily a neznečistily vývar',
      'Maso táhneme celkem 60 - 90 min, poté ho z vývaru vyndáme do ledové vody, aby zůstalo šťavnaté.',
      'Zázvor nakrájíme na 3mm plátky, cibuli necháme slupku a rozpůlíme ji a společně s badyánem, skořicí, kardamomem, hřebíčkem a koriandrovými semínky je opečeme a spálíme na pánvi. Koření jen lehce rozvoníme, hlavně ať se nespálí na uhel. Cibuli a zázvor můžeme vohulit víc.',
      'Spálenou cibuli očistíme od černého, sundáme slupku. Drobnější koření dáme do síťky na koření, aby se snadno dalo vyndat. Skořice, cibule a zázvor můžeme vložit do polévky jen tak. Vývar s kořením táhneme dalších 30 - 60 minut. Od teď polévka nesmí agresivně bublat, jinak všechno phoroma zmizí.',
      'Až koření vyndáme, polévku dočistíme a pokud je to potřeba, finálně dochutíme a to pouze solí, cukrem nebo troškou rybí omáčky.',
      'Nudle uvaříme dle návodu, propláchneme ledovou vodou a poté teplou – jedině tak nebudou lepit.',
      'Vložíme do misky, na ně pokládáme tenké plátky masa, mungo klíčky (pokud máme čerstvé, musí se pár sekund blanšírovat), jarní cibulku, chilli, čerstvý pepř a limetku. Zalijeme horkým vývarem (ohřejeme ho těsně pod bod varu, nesmí bublat!). Zamícháme a až po chvíli přidáme čerstvě nasekaný koriandr.',
      'V půlce je super přidat nakládaný česnek.'
    ],
    tips: [
      'Pokud máme přebytky koriandru jako jsou stonky či kořeny, nikdy je nevyhazujeme, ale očištěné je vyvaříme s kořením.',
      'NAKLÁDANÝ ČESNEK: česnek, chilli, cukr, sůl, citron/limeta. Česnek oloupeme a společně s chilli ho vložíme do vroucí vody. Po 1 min vyndáme česnek, po 2 min chilli. Česnek nasekáme na tenké plátky. Chilli nasekáme najemno. Vložíme do sklenice a zalijeme zálivkou z vyvařené vody (1 cup), cukru (0,5 cup), soli (1 tbsp) a citronovou/limetovou šťávu (0,5 cup). Necháme odležet nejlépe týden v lednici.',
    ],
  },
  {
    title: 'Ondřejova Pho Bo',
    order: 5,
    url: 'ondrejova-pho-bo',
    leadText: 'PHOck MSG! Tohle fáčko je BEZ botkaně/MSG/glutamanu. Místo jedné lžičky zvýrazňovače chuti ve vývaru musíme táhnout 4 jabka a kedlubnu a s dochucením se opravdu mazlit. A ani to botkaň zcela nenahradí, ale pokud chceme mít Pho ve zdravější verzi, než které dostaneme v 99 % restaurací, musíme tenhle zvýrazňovač oželit. A věřte, že až recept ozkoušíte, nebudete ho zas tak postrádat. Glutamátů do sebe sypete každý den mraky, tak tady uděláme výjimku. Váš domácí vývar bude mnohem silnější a nebude jen falešně ovoněný. Dobrou chuť a chci slyšet pořádný srkání!',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/dreceptar.appspot.com/o/pho-bo.jpg?alt=media&token=017b73e0-55a1-4928-a2f7-cae017902e47',
    createdAt: '8. 11. 2016',
    ingredients: [
      '5,5 l voda',
      '4-6 velkých morkových kostí',
      '1 Kg maso na vývar (žebra, přední s kostí, kližka apod.)',
      '0,5 Kg libové zadní',
      '4x jablko',
      '1x kedlubna',
      '2x cibule/větší šalotky',
      '2x jarní cibulka',
      '10 cm zázvor',
      '40x kardamom',
      '15x badyán',
      '10x skořice',
      '5x hřebíček',
      'hrst semínek koriandru',
      'rybí omáčka, citron, chilli',
      'koriandr a mungo klíčky',
      'nudle Pho'
    ],
    instructions: [
      'Morkové kosti s masem na vývar vložíme do hrnce, zalijeme studenou vodou a přivedeme k varu. Vaříme 10 minut a poté slijeme. Očistíme pod tekoucí vodou.',
      'Očištěné kosti a maso vložíme do umytého hrnce, zalijeme studenou vodou, přidáme lžíci soli a cukru, oloupanou cibuli/šalotky, rozčtvrtěná jablka a kedlubnu a přivedeme k varu.',
      'S varem se začne uvolňovat bílkovina ve formě pěny, tu pečlivě sbíráme, abychom měli co nejčistší vývar.',
      'Až se pěna přestane objevovat, můžeme vývar táhnout tak dlouho, jak jen můžeme. Minimálně 3 hodiny, ideálně alespoň 6 hodin.',
      'Po 30 - 60 min tažení vyndáme jablka, aby se nerozvařila a neznečistila vývar',
      'Maso po vytažení dáme do ledové vody, aby zůstalo šťavnaté. Kosti mohou ve vývaru zůstat až do konce.',
      'Zázvor nakrájíme na 3mm plátky, cibuli necháme slupku a rozpůlíme ji a společně s badyánem, skořicí, kardamomem, hřebíčkem a koriandrovými semínky je opečeme a spálíme na pánvi. Koření jen lehce rozvoníme, hlavně ať se nespálí na uhel. Cibuli a zázvor můžeme vohulit víc.',
      'Spálenou cibuli očistíme od černého, sundáme slupku. Drobnější koření dáme do síťky na koření, aby se snadno dalo vyndat. Skořice, cibule a zázvor můžeme vložit do polévky jen tak. Vývar s kořením táhneme dalších 30 - 60 minut. Od teď polévka nesmí agresivně bublat, jinak všechno phoroma zmizí.',
      'Až koření vyndáme, vyndáme s ním i kosti a vývar dočistíme a pokud je to potřeba, finálně dochutíme a to pouze solí, cukrem nebo troškou rybí omáčky.',
      'Nudle uvaříme dle návodu, propláchneme ledovou vodou a poté teplou – jedině tak nebudou lepit.',
      'Vložíme do misky, na ně pokládáme tenké plátky masa, mungo klíčky (pokud máme čerstvé, musí se pár sekund blanšírovat), jarní cibulku, chilli, čerstvý pepř a limetku. Zalijeme horkým vývarem (ohřejeme ho těsně pod bod varu, nesmí bublat!). Zamícháme a až po chvíli přidáme čerstvě nasekaný koriandr.',
      'V půlce je super přidat nakládaný česnek.'
    ],
    tips: [
      'Pokud máme přebytky koriandru jako jsou stonky či kořeny, nikdy je nevyhazujeme, ale očištěné je vyvaříme s kořením.',
      'NAKLÁDANÝ ČESNEK: česnek, chilli, cukr, sůl, citron/limeta. Česnek oloupeme a společně s chilli ho vložíme do vroucí vody. Po 1 min vyndáme česnek, po 2 min chilli. Česnek nasekáme na tenké plátky. Chilli nasekáme najemno. Vložíme do sklenice a zalijeme zálivkou z vyvařené vody (1 cup), cukru (0,5 cup), soli (1 tbsp) a citronovou/limetovou šťávu (0,5 cup). Necháme odležet nejlépe týden v lednici.',
    ],
  },
  {
    title: 'Ondřejovy tři frgále',
    order: 6,
    url: 'ondrejovy-tri-frgale',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/dreceptar.appspot.com/o/tri-frgale.jpg?alt=media&token=8272d932-1959-4ea5-999d-eb24f675481e',
    createdAt: '20. 2. 2021',
    leadText: 'Obyčejné, poctivé frgále. Ty žádné promo nepotřebujou. Využijete je nejlépe po O ke kafíčku.',
    ingredients: [
      '385 g hl. m. babišina na kynuté t.',
      '190 g polohrubá m.',
      '50+80 g cukr moučka',
      '170 g nemléko',
      '90+80 g nemáslo',
      '30 g čerstvé droždí',
      '2x žloutek',
      '8 g sůl',
      '1x kůra z celého citruse',
      'povidla',
      'jablečné pyré',
      'tvaroh',
      'rozinky namočené v rumu'
    ],
    instructions: [
      'Necháme si vzejít droždí s kapkou nemléka a cukru.',
      'Smícháme žloutky, cukr, sůl.',
      'Přidáme nemléko.',
      'Přisypeme mouku, vzešlé droždí, citronovou kůru a začneme hníst na rychlost 4. Po chvilce přidáme 90 g povoleného nemásla a hněteme celkem 10-15 minut.',
      'Těsto dotáhneme do koule a necháme ho kynout na teplejším místě 2 hodiny.',
      'DROBENKA: Mezitím, co těsto kyne, si připravíme drobenku. Na pánvi rozpustíme 80 g nemásla, v něm 80 g moučkového cukru a následně zasypeme 190 g polohrubé mouky. Drobenku opražíme, ale ne moc, aby nebyla tvrdá. Záleží, zda půjde na mokrý jablečný pomaz, nebo na sušší povidla.',
      'POMAZ: Na každý frgál přijde 400 g pomazu. Ředěná povidla se skořicí. Jablečné pyré s rozmačkanými hruškami a skořicí. Tvaroh smíchaný s 20 g cukru, 50 g nemásla, 2 žloutky a namočenými rozinkami v rumu. Záleží podle chuti.',
      'Po vykynutí těsto rozdělíme na tři 250g části.',
      'Každou část položíme na pečicí papír, uděláme z něj kouli a přikryjeme dalším papírem. Kouli rovnoměrně rozmáčkneme a začneme válet. Na plechu musí být těsto až do okrajů, jinak pomaz přeteče a vyteče. Když máme finální velikost, ostřihneme podle toho vrchní papír a přendáme do kulatého plechu.',
      'Rovnoměrně naneseme pomaz. Necháme volný okraj asi 1-2 cm. Posypeme třetinou drobenky. A nakonec se říká na jeden frgál lžíce rumu a lžíce másla. Ty rozpustíme, smícháme a potřeme jimi okraje před pečením.',
      'Pečeme na 190°C na horkovzduch v ocelovém plechu nebo na předehřátém kameni. Hustá povidla 12 minut. Řidší povidla nebo jablečný pomaz 13-14 minut.',
      'Ihned po vytažení z trouby frgál pokapeme zbytkem rumu s máslem.',
    ],
  },
  {
    title: 'Ondřejův Krtkův dort',
    order: 8,
    url: 'ondrejuv-krtkuv-dort',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/dreceptar.appspot.com/o/krtkuv-dort.jpg?alt=media&token=9e2c1d0d-59d1-4a78-981d-efdf086a4ed8',
    createdAt: '7. 5. 2021',
    leadText: 'Tradiční krtkův dort ve verzi bez mléka. Vyvinutý pro Kejtrsonku, která se ho přežrala k narozkám a už o něj moc nestojí. Tak ho lidi dávám aspoň vám.',
    ingredients: [
      '180 g polohrubá mouka',
      '125 ml nemléko',
      '100 ml olej',
      '100 + 40 g cukr moučka',
      '2x vejce',
      '1 lžíce rum',
      '2x lžíce hol. kakao',
      '1x prášek do pečiva',
      '3x banán',
      '125 g borůvky',
      '400 ml schlagfix',
      '35 g ztužovač',
      '80 g hořká čokoláda',
    ],
    instructions: [
      'Olej, cukr a žloutky ušleháme mixerem, přidáme rum.',
      'Mimo smícháme mouku, kakao a prášek do pečiva.',
      'Přidáme do mísy, smícháme, poté mléko.',
      'Nakonec opatrně vmícháme sníh z dvou bílků ušlehaný s troškou krupicového cukru. ',
      'Vlijeme do nemáslem vymazané formy vysypané kokosem. Pečeme na 180°C 30 minut.',
      'Necháme zchladnout. Po obvodu vytvoříme kruh 1 cm a vnitřek vydlabeme. Dno nesmí být porušené a moc mělké.',
      'NÁPLŇ: Ušleháme šlehačku s cukrem skoro dotuha. Přidáme ztužovač (Dr. Oetker 35 g smíchaný asi s 70 g vlažné vody). Došleháme a přidáme nahrubo nastrouhanou čokoládu.',
      'Podélně rozkrojené banány naklademe do vydlabaného korpusu. Na ně borůvky.',
      'Navrstvíme šlehačku a vytvoříme kopeček. Ten nakonec zasypeme rozdrobeným vnitřkem korpusu. Necháme pořádně zatuhnout a vychladit, alespoň 2 h vy nedočkavci!',
    ],
  },
  {
    title: 'Ondřejovy Sourdough Pancakes',
    order: 9,
    url: 'ondrejovy-sourdough-pancakes',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/dreceptar.appspot.com/o/sourdough-pancakes.jpg?alt=media&token=3404f178-5b95-4d55-951e-e0c6b71373ff',
    createdAt: '3. 3. 2022',
    leadText: 'Pečete chleba a nevíte co s kváskem? Narvěte ho všude, třeba do palačinek. Je to jednoduchý, rychlý a moc dobrý!',
    ingredients: [
      '400 g nemléko',
      '300 g hl. mouka, klidně celozrnná',
      '25 g cukr',
      '40 g aktivní kvásek',
      '1x vejce L',
      '50 g nemáslo',
      '3g sůl',
      '4g jedlá soda',
      'skořice, vanilka',
    ],
    instructions: [
      'VEČER PŘED: Smíchat nemléko, mouku, cukr a kvásek. Nechat odležet do rána, např. 8-12 hodin.',  
      'RÁNO: Přidat vajíčko, rozpuštěné máslo, sůl, skořici a jedlou sodu.',  
      'Pánev na medium. Každou palačinku smažíme na malinkém kousíčku másla uprostřed pánve tak na třetině pánve. Když se na vrchní straně udělají dírky, otočíme a doděláme 30-60 s. První strana trvá 2-3 min, podle barvy.',  
    ],
  },
  {
    title: 'Ondřejova Bunbáčka Nước chấm',
    order: 7,
    url: 'ondrejova-bunbacka',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/dreceptar.appspot.com/o/bunbacka.jpg?alt=media&token=07df5d3c-e7b0-4d13-8adc-e145511f623c',
    createdAt: '11. 9. 2019',
    leadText: 'Nước chấm je základní vietnamská omáčka. Nepostradatelná pro Bún bò Nam Bô, Bún chả nebo třeba Gỏi cuốn (čerstvé jarní závitky). Ve verzi pro závitky nám postačí pouze jedna mrkev a zeleninu sekáme na minikostičky.',
    ingredients: [
      '3x velká mrkev',
      '1x kedlubna',
      '5x stroužek česneku',
      '1-2x chilli',
      '5x lžíce fishsauce (alespoň 3O°)',
      '2x lžíce tř. cukr',
      '3/4 lžíce sůl',
      '1x lžíce vinný ocet',
      '1-2x limeta',
      '1,5 l vroucí voda',
    ],
    instructions: [
      'Mrkev a kedlubnu nakrájíme na julienne. Česnek zbavíme klíčků a propasírujeme ho. Chilli na tenká kolečka.',  
      'Vše dáme do hrnce a narveme tam všechny zbývající ingredience.',  
      'Zalijeme vroucí vodou a necháme chvíli odstát. Podáváme, až vychladne.',  
    ],
  },
  {
    title: 'Ondřejova kapří polévka',
    order: 10,
    url: 'ondrejova-kapri-polevka',
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/dreceptar.appspot.com/o/kapri-polevka.jpg?alt=media&token=35e02ad4-0aaf-45c3-ab46-0e17e12fd8db',
    createdAt: '24. 12. 2021',
    leadText: 'Naprostá nutnost při štědrovečerní večeři. Docela povedená verze, která stojí za zkoušku. Šafrán a muškátový oříšek to vytáhnout na úplně jiný level.',
    ingredients: [
      'kapří hlava, skelet a dostatek masa',
      '1x mrkev',
      '1x petržel',
      '1/2 malinký celer',
      '30 g nemáslo',
      '30 g hrubá mouka',
      '3x bobkový list',
      '8x nové koření',
      '10x pepř',
      'šafrán',
      'muškátový ořech',
      'kudrnka',
      'chlebové pepíky nasucho',
    ],
    instructions: [
      'Do 2 litrů osolené vody vložíme hlavu, skelet a kapří maso. Jakmile začne voda vařit, stopneme 15-20 minut. Dýl ne, ryba musí být čerstvá, ne vysušená.',
      'Vyndáme maso a vývar přecedíme.',
      'Nastrouháme mrkev, petržel a celer najemno. Na velké lžíci ramy osmažíme.',
      'Vyndáme z hrnce a rozpustíme v něm 30g ramy a přidáme 30g hrubé mouky. Vzniklou jíšku pořádně opražíme a zalijeme vývarem.',
      'Přihodíme do něj cca 10-20 blizen šafránu a nastrouháme kousek muškátového oříšku. Přivedeme k varu a chvilku provaříme.',
      'Obereme maso, pozor na kosti! a vložíme ho do zchladlé polévky, aby se nedovařilo.',
      'Nakrájíme domácí kváskový chlebík na kostičky a nasucho osmahneme na pánvi.',
      'Polévku v talíři ještě dozdobíme a dochutíme nasekanou petrželkou.',
    ],
  },
]

export default RECIPES_DATA;